/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function Room({ screenMeshRef, ...props }) {
  const { nodes, materials } = useGLTF('/final.gltf')

  useEffect(() => {
    // the GLTF bakes ambient occlusion and light maps that were designed for a different
    // lighting setup — zeroing them out lets our scene lights control the look instead
    Object.values(materials).forEach((mat) => {
      if (mat.aoMapIntensity !== undefined) mat.aoMapIntensity = 0;
      if (mat.lightMapIntensity !== undefined) mat.lightMapIntensity = 0;
    });
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      {/* standalone decorative mesh — lives outside the main scale group intentionally */}
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials['material_0.001']}
        position={[0.131, 0.064, 0.038]}
        rotation={[0, -0.797, 0]}
        scale={0.35}
      />
      {/* all scene objects are authored at roughly 100-unit scale in the GLTF, so we
          wrap them in scale={0.01} to keep world units in a sane range for the camera */}
      <group scale={0.01}>
        <group position={[3.69, 7.252, 2.412]} scale={[4.553, 1.722, 4.027]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube11001.geometry}
            material={materials.Block_2}
            position={[0.06, 0, 0]}
            scale={[0.9, 1, 1]}
          />
        </group>
        <group position={[3.718, 5.527, 2.464]} scale={[4.553, 1.722, 4.027]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube12001.geometry}
            material={materials.Block_4}
            position={[0.06, 0, 0]}
            scale={[0.9, 1, 1]}
          />
        </group>
        <group
          position={[-2.351, 8.19, 1.646]}
          scale={[7.16, 6.713, 5.599]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube13001.geometry}
            material={materials.monitor}
            scale={[1.14, 1, 1]}
          />
        </group>
        <group
          position={[3.642, 5.702, 4.348]}
          rotation={[0.08, 0, 0]}
          scale={[3.664, 0.439, 0.068]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube15001.geometry}
            material={materials.Cover_2}
            position={[0.09, 0, 0]}
          />
        </group>
        <group position={[2.814, 11.412, -6.282]} scale={[36.801, 23.697, 0.728]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube81001.geometry}
            material={materials.WALL_1}
            rotation={[0, 0, -Math.PI]}
            scale={-1}
          />
        </group>
        <group
          position={[3.642, 7.324, 4.297]}
          rotation={[0.08, 0, 0]}
          scale={[3.664, 0.439, 0.068]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube9001.geometry}
            material={materials.Cover_1}
            position={[0.07, 0, 0]}
          />
        </group>
        {/* ref attached here so MonitorController can project this group's world bounds
            to CSS coordinates for the overlay — must be the outermost screen transform */}
        <group
          ref={screenMeshRef}
          position={[-2.343, 8.312, 4.289]}
          scale={[4.946, 4.272, 0.46]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube93001.geometry}
            material={materials.screen1}
            scale={[1.11, 1, 0.9]}
          />
        </group>
        <group
          position={[-9.817, 11.853, -5.831]}
          rotation={[1.493, 0, 0]}
          scale={[2.635, 1, 1.911]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane3002.geometry}
            material={materials.PHOTOCARD}
            position={[0.001, 0.006, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane3003.geometry}
            material={materials.PHOTOCARD}
            position={[8.483, 0.49, -2.843]}
          />
        </group>
        <group
          position={[13.425, 19.003, -5.831]}
          rotation={[1.493, -0.015, -0.001]}
          scale={[2.635, 1, 1.911]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane6001.geometry}
            material={materials['PHOTOCARD.003']}
            position={[-8.774, -0.54, 3.934]}
            scale={0.8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane6002.geometry}
            material={materials['PHOTOCARD.002']}
            position={[-0.321, -0.06, 0.93]}
            scale={0.8}
          />
        </group>
        <group
          position={[-3.441, 16.547, -5.899]}
          rotation={[1.565, 0, 0]}
          scale={[7.655, 2.649, 10.398]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane7001.geometry}
            material={materials.poster_1}
            rotation={[0.01, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1_pCylinder10001.geometry}
          material={materials.button}
          position={[0.42, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1_pCylinder11001.geometry}
          material={materials.Screw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1_pCylinder9001.geometry}
          material={materials.plug_point_hole}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube94001.geometry}
          material={materials.timmer_board}
          position={[-8.637, 1.167, 3.959]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[3.009, 1.707, 1.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube95001.geometry}
          material={materials.timmer_board1}
          position={[-8.603, 1.976, 4.23]}
          scale={[1.705, 0.281, 0.332]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube96001.geometry}
          material={materials.timmer_screen}
          position={[-8.65, 1.128, 4.343]}
          rotation={[-0.233, 0, 0]}
          scale={[2.648, 1.292, 0.205]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube1001.geometry}
          material={materials.block_2}
          position={[0, 1.141, 0]}
          scale={[12.511, 1.979, 9.196]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube10001.geometry}
          material={materials.block_1}
          position={[0, 3.399, 0.044]}
          scale={[12.461, 2.513, 9.137]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube14001.geometry}
          material={materials.computer_stand}
          position={[-2.293, 4.754, 1.63]}
          scale={[5.812, 0.205, 5.376]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube17001.geometry}
          material={materials.back_board}
          position={[-2.525, 7.893, -1.176]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[5.812, 0.142, 4.574]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube18001.geometry}
          material={materials.back_board1}
          position={[-2.525, 7.893, -1.325]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[4.287, 0.281, 3.374]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube19001.geometry}
          material={materials.Keyboard}
          position={[0, 0.914, 8.057]}
          scale={[10.711, 1.244, 5.34]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube2001.geometry}
          material={materials.Button_2}
          position={[5.612, 1.139, 4.233]}
          scale={[0.196, 1.356, 0.322]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube20001.geometry}
          material={materials.block_cover_2}
          position={[-3.07, 3.417, 4.455]}
          scale={[5.017, 1.495, 0.167]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube21001.geometry}
          material={materials.block_3}
          position={[-4.464, 3.423, 4.473]}
          scale={[1.788, 1.192, 0.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube22001.geometry}
          material={materials.button_1}
          position={[-4.465, 3.458, 4.494]}
          scale={[0.518, 0.383, 0.142]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube23001.geometry}
          material={materials.button_4}
          position={[-2.43, 3.769, 4.471]}
          scale={[1.917, 0.324, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube24001.geometry}
          material={materials.button_3}
          position={[-3.232, 3.383, 4.473]}
          scale={[0.745, 0.277, 0.057]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube3001.geometry}
          material={materials.Button_1}
          position={[5.143, 1.139, 4.233]}
          scale={[0.196, 1.356, 0.322]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube65001.geometry}
          material={materials.space_bar_1}
          position={[-4.007, 0.923, 9.263]}
          scale={[1.427, 0.621, 0.621]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube66001.geometry}
          material={materials.Space_bar_2}
          position={[4.411, 0.988, 9.263]}
          scale={[1.007, 0.621, 0.621]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube68001.geometry}
          material={materials.Space_bar}
          position={[1.104, 0.963, 10.09]}
          scale={[1.427, 0.391, 0.503]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube73001.geometry}
          material={materials.Mouse}
          position={[9.423, 0.802, 8.263]}
          scale={[2.185, 1.074, 3.304]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube74001.geometry}
          material={materials.Mouse_cover}
          position={[9.429, 1.368, 7.134]}
          scale={[1.795, 0.294, 0.729]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube75001.geometry}
          material={materials.cd_1}
          position={[6.557, 2.757, 2.323]}
          scale={[0.49, 4.99, 3.462]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube76001.geometry}
          material={materials.cd_2}
          position={[7.126, 2.757, 2.323]}
          rotation={[0, 0, 0.028]}
          scale={[0.515, 4.99, 3.462]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube78001.geometry}
          material={materials.cd_3}
          position={[7.716, 2.757, 2.323]}
          rotation={[0, 0, 0.054]}
          scale={[0.515, 4.99, 3.462]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube8001.geometry}
          material={materials.block_cover_1}
          position={[0, 3.4, 4.375]}
          scale={[12.045, 2.016, 0.255]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube83001.geometry}
          material={materials.computer_mat}
          position={[2.769, 0.17, 2.344]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[29.564, 20.289, 0.253]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube85001.geometry}
          material={materials.aiStandardSurface6}
          position={[11.881, 2.916, -5.91]}
          scale={[2.256, 2.256, 0.495]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube87001.geometry}
          material={materials.Button_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube89001.geometry}
          material={materials.Number}
          position={[0, 0.146, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube90001.geometry}
          material={materials.Alphabets}
          position={[0, 0.113, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube91001.geometry}
          material={materials.Control_Button}
          position={[0, 0.09, 0.181]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube92001.geometry}
          material={materials.black_board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube97001.geometry}
          material={materials.WALL_2}
          position={[2.769, 0.74, -6.117]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[36.801, 1.5, 1.237]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube98001.geometry}
          material={materials.DESK}
          position={[2.814, -0.33, 5.938]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[36.801, 23.697, 0.728]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2001.geometry}
          material={materials.button_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3001.geometry}
          material={materials.material}
          position={[-8.664, 1.431, 9.013]}
          rotation={[-Math.PI, 0.19, -Math.PI]}
          scale={1.067}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pDisc1001.geometry}
          material={materials.COFFEE}
          position={[-8.674, 2.115, 8.962]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane8001.geometry}
          material={materials.poster_2}
          position={[6.024, 14.101, -5.831]}
          rotation={[1.565, 0, 0]}
          scale={[7.655, 2.649, 10.398]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere5001.geometry}
          material={materials.button_5}
          position={[0.23, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere6001.geometry}
          material={materials.Button_6}
          position={[0.26, 0, 0]}
        />
      </group>
    </group>
  )
}

// preload kicks off the GLTF fetch before the component mounts, so there's no pop-in on first render
useGLTF.preload('/final.gltf')
